# Generated by Django 2.2.5 on 2019-09-09 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0005_auto_20190909_0349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='updater',
        ),
        migrations.RemoveField(
            model_name='security',
            name='updater',
        ),
        migrations.AddField(
            model_name='description',
            name='country',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='port.Security'),
        ),
    ]
