# Generated by Django 2.2.5 on 2019-09-13 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0007_auto_20190912_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='port.Security'),
        ),
    ]
